In [92]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

In [3]:
soil_west = pd.read_csv("../soil/soil_data_west.csv")
soil_east = pd.read_csv("../soil/soil_data_east.csv")
soil_740 = pd.read_csv("../soil/soil_data_740.csv")
soil_750 = pd.read_csv("../soil/soil_data_750.csv")

In [5]:
soil = pd.concat([soil_west, soil_east, soil_740, soil_750])
soil.shape

(296951, 9)

In [8]:
parcel_crop = pd.read_csv("../joined_combined_filtered_df_td_27_3.csv")
parcel_crop.shape

(25268, 145)

In [10]:
parcel_crop_soil = pd.merge(left = parcel_crop, right = soil, on = "parcelnumb", how = "left")
parcel_crop_soil.shape

(25324, 153)

In [14]:
water_usage_df = pd.read_csv("CropWaterUsage.csv")

In [16]:
parcel_crop_soil_water = pd.merge(left = parcel_crop_soil, right = water_usage_df, on = "Crop2016", how = "left")

In [17]:
for col in parcel_crop_soil_water.columns:
    print(col)

Unnamed: 0_x
geoid
sourceagent
parcelnumb
usecode
usedesc
zoning
zoning_description
struct
multistruct
structno
yearbuilt
numstories
numunits
structstyle
parvaltype
improvval
landval
parval
agval
saleprice
saledate
taxamt
owntype
owner
ownfrst
ownlast
owner2
owner3
owner4
subsurfown
subowntype
mailadd
mail_address2
careof
mail_addno
mail_addpref
mail_addstr
mail_addsttyp
mail_addstsuf
mail_unit
mail_city
mail_state2
mail_zip
mail_urbanization
address
address2
saddno
saddpref
saddstr
saddsttyp
saddstsuf
sunit
scity
original_address
city
county
state2
szip
urbanization
location_name
address_source
legaldesc
plat
book
page
block
lot
neighborhood
subdivision
census_tract
census_block
census_blockgroup
sourceref
sourcedate
sourceurl
recrdareatx
recrdareano
gisacre
sqft
reviseddate
path
ll_stable_id
ll_uuid
ll_updated_at
lbcs_activity
lbcs_function
lbcs_structure
lbcs_site
lbcs_ownership
homeowner_exemp
lot_area
pers_prop_val
tax_area_code
contract_number
contract_year
non_renewal_year
use_h

In [83]:
#usecode, #scity

feature_df = parcel_crop_soil_water[["ll_gisacre", "pers_prop_val", "homeowner_exemp", "TotalWater", "irrcapcl", "nirrcapcl", "parval"]]
feature_df.shape

(25324, 7)

In [84]:
feature_df = feature_df.dropna()

In [85]:
X = feature_df[feature_df.columns[0:6]].values

In [86]:
y = feature_df[feature_df.columns[6]].values

In [93]:
#regr = RandomForestRegressor(oob_score = True)
regr = LinearRegression()

In [94]:
regr.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [95]:
regr.coef_

array([ 4.89725084e+03,  1.25316939e+00,  4.25442887e+00,  3.74443845e+04,
       -3.41176703e+03, -6.38151896e+04])

In [96]:
regr.score(X,y)

0.3325772499083484

In [89]:
regr.oob_score_

0.16797401286633884

In [90]:
regr.feature_importances_

array([0.51493345, 0.31301922, 0.00419487, 0.10545991, 0.04323288,
       0.01915967])

In [101]:
regr.predict([[34,0,0,5,1,1]])

array([594969.82284903])

In [74]:
feature_df

ll_gisacre  pers_prop_val  homeowner_exemp  TotalWater  irrcapcl  \
0        16.97049            0.0              0.0    2.926667       2.0   
1         8.68291            0.0              0.0    4.360258       3.0   
3        20.13240            0.0              0.0    3.223960       3.0   
7         2.14084            0.0           7000.0    4.467857       4.0   
28       19.79715            0.0              0.0    4.603704       1.0   
...           ...            ...              ...         ...       ...   
25317    17.36936            0.0              0.0    4.413095       2.0   
25318    25.45396        40810.0              0.0    2.926667       1.0   
25319    33.98161            0.0              0.0    4.043617       1.0   
25321    18.56196            0.0              0.0    4.603704       2.0   
25323    13.75780            0.0              0.0    4.948810       1.0   

          parval  
0       294187.0  
1        72821.0  
3       162075.0  
7       234449.0  
28     1867425.0  
...          ...  
25317  1953871.0  
25318   316219.0  
25319   254344.0  
25321   250908.0  
25323   324041.0  

[21564 rows x 6 columns]